### ISSUE TITLE
Redundant code in src/main/java/fr/unistra/pelican/algorithms/conversion/RGBToIHLS.java

### ISSUE THREAD

**Issue by lishichengyan** [PelicanTeam/pelican#2]
Hi there, I see the following code in ```src/main/java/fr/unistra/pelican/algorithms/conversion/RGBToIHLS.java```:

```
if(underFrac==0||upperFrac/underFrac<=-1||upperFrac/underFrac>=1)			
  hPrime=0;
```

This sanity check appears twice (line 103-104 and line 115-116) However line 115-116 seems redundant because the computation is done.

Thanks for your attention.

**Comment by JjmWeber** [comment]
Thx, I correct it.
